create table shoe_lasts (
    shoe_last_id int generated by default as identity not null primary key,

    last_code varchar(30) not null unique,
    last_name varchar(40) not null,

    last_type varchar(40) not null,
    gender_category varchar(20),
    size_system varchar(20) not null,
    base_size numeric(4,1) not null,

    toe_shape varchar(40),

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table shoe_last_sizes (
    shoe_last_size_id int generated by default as identity not null primary key,

    shoe_last_id int not null,

    size_value numeric(4,1) not null,

    heel_height_mm numeric(5,1),
    instep_height_mm numeric(5,1),
    ball_girth_mm numeric(5,1),
    waist_girth_mm numeric(5,1),
    overall_length_mm numeric(5,1),

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint fk_shoe_last_sizes_shoe_last
        foreign key (shoe_last_id) references shoe_lasts(shoe_last_id),

    constraint uq_shoe_last_sizes_shoe_last_size
        unique (shoe_last_id, size_value)
);

create table shoe_construction_methods (
    construction_method_id int generated by default as identity not null primary key,

    construction_method_code varchar(40) not null unique,
    construction_method_name varchar(80) not null,

    difficulty_level varchar(30),

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table material_categories (
    material_category_id int generated by default as identity not null primary key,

    material_category_code varchar(40) not null unique,
    material_category_name varchar(80) not null,

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table material_attributes (
    material_attribute_id int generated by default as identity not null primary key,

    material_attribute_code varchar(40) not null unique,
    material_attribute_name varchar(80) not null,

    value_type varchar(30) not null,
    unit_of_measure varchar(20),

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint chk_material_attributes_value_type
        check (value_type in ('text', 'numeric', 'boolean'))
);

create table material_usage_roles (
    material_usage_role_id int generated by default as identity not null primary key,

    material_role_code varchar(40) not null unique,
    material_role_name varchar(80) not null,

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table materials (
    material_id int generated by default as identity not null primary key,

    material_category_id int not null,

    material_code varchar(80) not null unique,
    material_name varchar(120) not null,

    unit_of_measure varchar(20) not null,

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint fk_materials_material_category
        foreign key (material_category_id) references material_categories(material_category_id)
);

create table material_attribute_values (
    material_attribute_value_id int generated by default as identity not null primary key,

    material_id int not null,
    material_attribute_id int not null,

    value_text text,
    value_numeric numeric(10,3),
    value_boolean boolean,

    description text,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint fk_material_attribute_values_material
        foreign key (material_id) references materials(material_id),

    constraint fk_material_attribute_values_attribute
        foreign key (material_attribute_id) references material_attributes(material_attribute_id),

    constraint uq_material_attribute_values_material_attribute
        unique (material_id, material_attribute_id),

    constraint chk_material_attribute_values_single_value
        check (
            (value_text is not null)::int +
            (value_numeric is not null)::int +
            (value_boolean is not null)::int = 1
        )
);

create table shoe_models (
    shoe_model_id int generated by default as identity not null primary key,

    shoe_last_id int not null,

    model_code varchar(60) not null unique,
    model_name varchar(100) not null,

    season varchar(40),
    model_purpose varchar(80),

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint fk_shoe_models_shoe_last
        foreign key (shoe_last_id) references shoe_lasts(shoe_last_id)
);

create table shoe_model_classes (
    shoe_model_class_id int generated by default as identity not null primary key,

    shoe_model_id int not null,
    construction_method_id int not null,

    class_code varchar(40) not null,
    class_name varchar(80) not null,

    quality_level varchar(40),
    warranty_months int,

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint fk_shoe_model_classes_shoe_model
        foreign key (shoe_model_id) references shoe_models(shoe_model_id),

    constraint fk_shoe_model_classes_construction_method
        foreign key (construction_method_id) references shoe_construction_methods(construction_method_id),

    constraint uq_shoe_model_classes_model_class
        unique (shoe_model_id, class_code)
);
