create table shoe_lasts (
    shoe_last_id int generated by default as identity not null primary key,

    last_code varchar(30) not null unique,
    last_name varchar(40) not null,

    last_type varchar(40) not null,
    gender_category varchar(20),
    size_system varchar(20) not null,
    base_size numeric(4,1) not null,

    toe_shape varchar(40),

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table shoe_last_sizes (
    shoe_last_size_id int generated by default as identity not null primary key,

    shoe_last_id int not null,

    size_value numeric(4,1) not null,

    heel_height_mm numeric(5,1),
    instep_height_mm numeric(5,1),
    ball_girth_mm numeric(5,1),
    waist_girth_mm numeric(5,1),
    overall_length_mm numeric(5,1),

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint fk_shoe_last_sizes_shoe_last
        foreign key (shoe_last_id) references shoe_lasts(shoe_last_id),

    constraint uq_shoe_last_sizes_shoe_last_size
        unique (shoe_last_id, size_value)
);

create table shoe_construction_methods (
    construction_method_id int generated by default as identity not null primary key,

    construction_method_code varchar(40) not null unique,
    construction_method_name varchar(80) not null,

    difficulty_level varchar(30),

    description text,

    is_active boolean not null default true,

    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);
